# Generated by Django 3.0.14 on 2023-03-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addId', models.AutoField(primary_key=True, serialize=False)),
                ('shop_Flat_House_No', models.CharField(max_length=5)),
                ('street_Address', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=160)),
                ('categoryDescription', models.TextField()),
                ('categoryDateAdded', models.DateTimeField(auto_now_add=True)),
                ('categoryLastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=160)),
                ('CustomerContact', models.CharField(max_length=12)),
                ('CustomerEmail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('deliveryId', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryDate', models.DateTimeField()),
                ('deliveryTime', models.DateTimeField()),
                ('deliveryCharges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Customer')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('BatchNumber', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=100)),
                ('BatchPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateAdded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderCoupon', models.CharField(max_length=20, null=True)),
                ('orderTotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderStatus', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=160)),
                ('productDescription', models.TextField()),
                ('productQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productImage', models.ImageField(upload_to='Products/')),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productWeight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productOfferPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('productDiscount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('productStatus', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Category')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sellerID', models.AutoField(primary_key=True, serialize=False)),
                ('sellerName', models.CharField(max_length=160)),
                ('sellerShopName', models.CharField(max_length=160)),
                ('sellerContact', models.CharField(max_length=12)),
                ('sellerEmail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlistId', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('rating', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Customer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Seller'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(max_length=100)),
                ('cc_Type', models.CharField(max_length=100, null=True)),
                ('cc_Owner', models.CharField(max_length=100, null=True)),
                ('cc_Number', models.CharField(max_length=100, null=True)),
                ('cc_Expiry', models.CharField(max_length=100, null=True)),
                ('paymentStatus', models.CharField(max_length=100)),
                ('paymentDate', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('orderItemId', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Seller'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Seller'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Payment'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couponId', models.AutoField(primary_key=True, serialize=False)),
                ('couponCode', models.CharField(max_length=20)),
                ('couponStatus', models.CharField(max_length=60)),
                ('couponText', models.TextField()),
                ('couponDiscountType', models.CharField(max_length=100)),
                ('couponDateAdded', models.DateTimeField(auto_now_add=True)),
                ('couponLastUpdated', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
                ('productQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productTotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmartApp.Product')),
            ],
        ),
    ]
