# Generated by Django 3.0.14 on 2023-03-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
